### ISSUE TITLE
Search does not work!

### ISSUE THREAD

**Issue by MarcHumes** [nodeful/Faceply.io#2]
The search function does not work, leaving this project dead in the water. Please fix it, this could be a really great tool!

**Comment by nodeful** [comment]
I don't really use the application myself. I only needed it for a brief moment in my life. I can't invest any of my personal time into this, sorry. Though I'm happy to merge a pull request if someone is willing to fix it.

Roman

**Comment by nodeful** [comment]
and also duplicate of #1
