### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by claxonberlin** [nodeful/Faceply.io#5]
Hi

The website doesn't seem to exist anymore.

**Comment by mursec** [comment]
I hope this project gets picked backup. Does not seem to work for me.

**Comment by rasved** [comment]
This is not solved: ERR_NAME_NOT_RESOLVED

**Comment by adamzea** [comment]
Still seems to be down. 
DNS_PROBE_FINISHED_NXDOMAIN
